//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shares
{
    using System;
    using System.Collections.Generic;
    
    public partial class Share
    {
        public long ShareId { get; set; }
        public Nullable<long> LFNo { get; set; }
        public string CertificateNo { get; set; }
        public string PersonToWhomTransfered { get; set; }
        public Nullable<long> NoOfShares { get; set; }
        public Nullable<long> DistinctiveFromNo { get; set; }
        public Nullable<long> DistinctiveToNo { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
        public string MobileNumber { get; set; }
        public string AadhaarNumber { get; set; }
        public string PanNumber { get; set; }
        public string VoterNumber { get; set; }
        public string RationCardNumber { get; set; }
        public string BankAccountNumber { get; set; }
        public string BankDetails { get; set; }
        public string OptionalColumnOne { get; set; }
        public string OptionalColumnTwo { get; set; }
    }
}
